import React, {useContext} from 'react';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import {OrderListContext} from '../../contexts/OrderListContext';

import ClothingIconsList from '../../clothinIcons';
import TableContentCentered from '../../components/TableContentCentered';
import {AnnotationContainer} from '../../components/AnnotationsBox/styles';

const Report = () => {
  const {orderListItems, orderListItemsNotes} = useContext(OrderListContext);

  console.log('orderListItemsNotes', orderListItemsNotes);
  console.log('orderListItems', orderListItems);

  return (
    <>
      <Row>
        <Col>&nbsp;</Col>
      </Row>
      <Row>
        <Col xs="6">
          <h5>MASCULINO</h5>
          <TableContentCentered>
            <thead>
              <tr>
                <th>-</th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
            </tbody>
          </TableContentCentered>
        </Col>

        <Col xs="6">
          <h5>FEMININO</h5>
          <TableContentCentered>
            <thead>
              <tr>
                <th>-</th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
            </tbody>
          </TableContentCentered>
        </Col>
      </Row>

      <Row className="mt-4">
        <Col xs="6">
          <h5>INFANTIL</h5>
          <TableContentCentered>
            <thead>
              <tr>
                <th>-</th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
            </tbody>
          </TableContentCentered>
        </Col>

        <Col xs="6">
          <h5>ANOTAÇÕES</h5>
          <AnnotationContainer>
            {orderListItemsNotes.split('\n').map((line) => (
              <p>{line}</p>
            ))}
          </AnnotationContainer>
        </Col>
      </Row>
    </>
  );
};

export default Report;
