import React, {useContext} from 'react';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import {OrderListContext} from '../../contexts/OrderListContext';

import ClothingIconsList from '../../clothinIcons';
import TableContentCentered from '../../components/TableContentCentered';
import {AnnotationContainer} from '../../components/AnnotationsBox/styles';
import PenField from '../../components/PenField';
import ReportHeader from '../../components/ReportHeader';

const Report = () => {
  const {orderListItems, orderListItemsNotes} = useContext(OrderListContext);

  console.log('orderListItemsNotes', orderListItemsNotes);
  console.log('orderListItems', orderListItems);

  return (
    <>
      <Row className="mt-5">
        {/* LEFT SIDE */}
        <Col xs="6">
          <ReportHeader
            title="SISBot"
            subtitle="Relatório de Processamento"
            date="10 de Janeiro de 2021 - 10h31"
          />
        </Col>

        {/* RIGHT SIDE */}
        <Col xs="6">
          <PenField label="Cliente:" />
          <PenField label="Data do Pedido:" />
          <PenField label="Data de Entrega:" />
          <PenField label="Responsável:" />
        </Col>
      </Row>

      <Row className="mt-5">
        <Col xs="6">
          <h5>MASCULINO</h5>
          <TableContentCentered>
            <thead>
              <tr>
                <th>-</th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
            </tbody>
          </TableContentCentered>
        </Col>

        <Col xs="6">
          <h5>FEMININO</h5>
          <TableContentCentered>
            <thead>
              <tr>
                <th>-</th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
            </tbody>
          </TableContentCentered>
        </Col>
      </Row>

      <Row className="mt-4">
        <Col xs="6">
          <h5>INFANTIL</h5>
          <TableContentCentered>
            <thead>
              <tr>
                <th>-</th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
                <th>
                  <img
                    src={ClothingIconsList.tshirt}
                    alt="clothing"
                    height={25}
                  />
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
              <tr>
                <td>PP</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              </tr>
            </tbody>
          </TableContentCentered>
        </Col>

        <Col xs="6">
          <h5>ANOTAÇÕES</h5>
          <AnnotationContainer>
            {orderListItemsNotes.split('\n').map((line) => (
              <p>{line}</p>
            ))}
          </AnnotationContainer>
        </Col>
      </Row>
    </>
  );
};

export default Report;
